name: mathsaide
description: A project to assist study with learnig disability (Dyscaculia) to solve maths problems effectively
publish_to: "none"
version: 1.2.2+5

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  # firebase_core: ^2.3.0
  firebase_auth: ^5.3.3
  # firebase_auth: ^4.1.5
  firebase_storage: ^12.3.6
  # firebase_storage: ^11.0.6
  cloud_firestore: ^5.5.0
  # cloud_firestore: ^4.1.0
  firebase_remote_config:
  resize:
  cached_network_image: ^3.2.3
  google_fonts:
  image_picker: ^1.0.2
  image_cropper: ^5.0.0
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  path_provider: ^2.0.11
  flutter_keyboard_visibility: ^5.4.0
  connectivity_plus: ^4.0.1
  http: 1.1.0
  math_keyboard: ^0.3.2
  intl:
  package_info_plus: ^4.1.0
  url_launcher: ^6.0.12
  flutter_markdown: ^0.7.3+2
  flutter_tex: 5.1.8
  flutter_math_fork: 0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.16

flutter_native_splash:
  color: "#E0F2F1"
  image: assets/images/launcher.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
