name: mathsaide
description: "A project to assist study with learnig disability (Dyscaculia) to solve maths problems effectively"
publish_to: "none"
version: 1.2.2+5

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  # firebase_core: ^2.3.0
  firebase_auth: ^5.6.0
  # firebase_auth: ^4.1.5
  firebase_storage: ^12.4.7
  # firebase_storage: ^11.0.6
  cloud_firestore: ^5.5.0
  # cloud_firestore: ^4.1.0
  firebase_remote_config: ^5.4.5
  resize:
  cached_network_image: ^3.4.1
  google_fonts:
  image_picker: ^1.1.2
  # image_cropper: ^6.0.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  path_provider: ^2.1.5
  flutter_keyboard_visibility: ^6.0.0
  connectivity_plus: ^6.1.4
  http: 1.4.0
  math_keyboard: 0.3.2
  intl:
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  flutter_markdown: ^0.7.7
  # flutter_tex: 5.1.8
  flutter_math_fork: 0.7.3
  # latext: ^0.5.0
  flutter_markdown_plus_latex: ^1.0.1
  easy_latex: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.2.16

flutter_native_splash:
  color: "#E0F2F1"
  image: assets/images/launcher.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
