// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG5lZqCGFAvk8tHRsypgW5q3epX8ntQuM',
    appId: '1:513703573923:web:7b2a9985f7716188c78216',
    messagingSenderId: '513703573923',
    projectId: 'mathsaide-780f5',
    authDomain: 'mathsaide-780f5.firebaseapp.com',
    storageBucket: 'mathsaide-780f5.appspot.com',
    measurementId: 'G-HJVSBS4H4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARnc3KIE_0ajOHc6hezcFz5rSoDkZ6H-M',
    appId: '1:513703573923:android:255bac61de3ced15c78216',
    messagingSenderId: '513703573923',
    projectId: 'mathsaide-780f5',
    storageBucket: 'mathsaide-780f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWoLqEd8rAh1Sdg7cXiDBx30uzV3GlofQ',
    appId: '1:513703573923:ios:fab5cffa23aae30ec78216',
    messagingSenderId: '513703573923',
    projectId: 'mathsaide-780f5',
    storageBucket: 'mathsaide-780f5.appspot.com',
    iosClientId: '513703573923-rjclgmc21fapr53j1pbp0qr7c6eetj17.apps.googleusercontent.com',
    iosBundleId: 'com.suptle.mathsaide',
  );

}